### ISSUE TITLE
Implement PropertyChanged.Fody

### ISSUE THREAD

**Issue by sebleg** [JustForFunDeveloper/HS-Feed-Suite#3]
To save many code lines and to get more overview in the view model classes it would be a good solution to add the NuGet package PropertyChanged.Fody in the project.

It implements the OnPropertyChanged() statement to all classes that implement INotifyPropertyChanged. See on GitHub: [https://github.com/Fody/PropertyChanged](https://github.com/Fody/PropertyChanged)

For example the following code lines in **MainViewModel.cs**
``` 
public bool IsFlyoutOpen
{
  get { return _isFlyoutOpen; }
  set
  {
    _isFlyoutOpen = value;
    OnPropertyChanged();
  }
}
```
could then look like this (with same behaviour):

```public bool IsFlyoutOpen {get; set;}```

**Comment by JustForFunDeveloper** [comment]
Thank you very much for this suggestion!

This looks pretty neat, i already thought that the HomeViewModel is quite code heavy. 
So this will clean it up a bit.

I'll definitly try to add this in the next release.
